### ISSUE TITLE
[BUG]I NEED YOUR HELP

### ISSUE THREAD

**Issue by LXY010327** [bukkitcommons/QuickShop-Rev#14]
[01:39:12] [Server thread/ERROR] [Minecraft]: 加载插件 plugins/QuickShop-rev.3.1.5.jar 失败(java.lang.ClassNotFoundException: org.bukkit.craftbukkit.Main),详细请查看debug.log
[01:39:12] [Server thread/DEBUG] [FML]: Could not load 'plugins/QuickShop-rev.3.1.5.jar' in folder 'plugins
org.bukkit.plugin.InvalidPluginException: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.Main
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[JavaPluginLoader.class:git-CatServer-1.12.2-2019-11-27]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:git-CatServer-1.12.2-2019-11-27]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [SimplePluginManager.class:git-CatServer-1.12.2-2019-11-27]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:359) [CraftServer.class:git-CatServer-1.12.2-2019-11-27]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:352) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:324) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:621) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.Main
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:110) ~[PluginClassLoader.class:git-CatServer-1.12.2-2019-11-27]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:99) ~[PluginClassLoader.class:git-CatServer-1.12.2-2019-11-27]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
	at catserver.server.remapper.ReflectionMethods.forName(ReflectionMethods.java:23) ~[ReflectionMethods.class:git-CatServer-1.12.2-2019-11-27]
	at catserver.server.remapper.ReflectionMethods.forName(ReflectionMethods.java:17) ~[ReflectionMethods.class:git-CatServer-1.12.2-2019-11-27]
	at cc.bukkit.shop.logger.ShopPluginLogger.<init>(ShopPluginLogger.java:152) ~[?:?]
	at cc.bukkit.shop.logger.ShopLogger.<init>(ShopLogger.java:29) ~[?:?]
	at cc.bukkit.shop.logger.ShopLogger.<init>(ShopLogger.java:6) ~[?:?]
	at cc.bukkit.shop.logger.ShopLogger$Singleton.<init>(ShopLogger.java:24) ~[?:?]
	at cc.bukkit.shop.logger.ShopLogger$Singleton.<init>(ShopLogger.java:20) ~[?:?]
	at cc.bukkit.shop.logger.ShopLogger.initalize(ShopLogger.java:8) ~[?:?]
	at org.maxgamer.quickshop.QuickShop.<init>(QuickShop.java:280) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:89) ~[PluginClassLoader.class:git-CatServer-1.12.2-2019-11-27]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-2019-11-27]
	... 7 more

**Comment by sotr2333** [comment]
你好，本插件暂时不支持你使用的服务端，将尽快修复
